services:
  - type: web
    name: hems-backend
    env: python
    pythonVersion: '3.12'
    buildCommand: "bash BACKEND/hems_backend/render-build.sh"
    startCommand: "bash BACKEND/hems_backend/render-start.sh"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: hems-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
databases:
  - name: hems-db
    plan: free