# Generated by Django 5.2.10 on 2026-02-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_appliance_energyusage_usage_emission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedDeviceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        help_text="Building name or identifier", max_length=100
                    ),
                ),
                (
                    "room",
                    models.CharField(help_text="Room number or name", max_length=50),
                ),
                (
                    "light_2x2_count",
                    models.IntegerField(default=0, help_text="Count of 2x2 lights"),
                ),
                (
                    "light_2x2_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for 2x2 lights", null=True
                    ),
                ),
                (
                    "led_tb_count",
                    models.IntegerField(
                        default=0, help_text="Count of LED tube lights"
                    ),
                ),
                (
                    "led_tb_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for LED tube lights", null=True
                    ),
                ),
                (
                    "sensor_light_count",
                    models.IntegerField(default=0, help_text="Count of sensor lights"),
                ),
                (
                    "sensor_light_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for sensor lights", null=True
                    ),
                ),
                (
                    "round_tb_count",
                    models.IntegerField(
                        default=0, help_text="Count of round tube lights"
                    ),
                ),
                (
                    "round_tb_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for round tube lights", null=True
                    ),
                ),
                (
                    "floode_count",
                    models.IntegerField(default=0, help_text="Count of flood lights"),
                ),
                (
                    "floode_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for flood lights", null=True
                    ),
                ),
                (
                    "circle_light_count",
                    models.IntegerField(default=0, help_text="Count of circle lights"),
                ),
                (
                    "circle_light_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for circle lights", null=True
                    ),
                ),
                (
                    "c_fan_count",
                    models.IntegerField(default=0, help_text="Count of ceiling fans"),
                ),
                (
                    "c_fan_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for ceiling fans", null=True
                    ),
                ),
                (
                    "wall_fan_count",
                    models.IntegerField(default=0, help_text="Count of wall fans"),
                ),
                (
                    "wall_fan_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for wall fans", null=True
                    ),
                ),
                (
                    "table_fan_count",
                    models.IntegerField(default=0, help_text="Count of table fans"),
                ),
                (
                    "table_fan_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for table fans", null=True
                    ),
                ),
                (
                    "exhaust_fan_count",
                    models.IntegerField(default=0, help_text="Count of exhaust fans"),
                ),
                (
                    "exhaust_fan_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for exhaust fans", null=True
                    ),
                ),
                (
                    "cooler_count",
                    models.IntegerField(default=0, help_text="Count of coolers"),
                ),
                (
                    "cooler_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for coolers", null=True
                    ),
                ),
                (
                    "ac_count",
                    models.IntegerField(
                        default=0, help_text="Count of air conditioners"
                    ),
                ),
                (
                    "ac_company",
                    models.CharField(
                        blank=True,
                        help_text="AC manufacturer/company",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ac_star_rating",
                    models.IntegerField(
                        blank=True, help_text="AC star rating (1-5)", null=True
                    ),
                ),
                (
                    "ac_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for AC", null=True
                    ),
                ),
                (
                    "ac_ton",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AC tonnage (0.75, 1, 1.5, 2, 2.5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "ac_iseer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="ISEER rating (3.0-6.5)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "projector_count",
                    models.IntegerField(default=0, help_text="Count of projectors"),
                ),
                (
                    "projector_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for projectors", null=True
                    ),
                ),
                (
                    "pc_count",
                    models.IntegerField(default=0, help_text="Count of PCs/computers"),
                ),
                (
                    "pc_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for PCs", null=True
                    ),
                ),
                (
                    "printer_count",
                    models.IntegerField(default=0, help_text="Count of printers"),
                ),
                (
                    "printer_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for printers", null=True
                    ),
                ),
                (
                    "rf_count",
                    models.IntegerField(default=0, help_text="Count of refrigerators"),
                ),
                (
                    "rf_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for refrigerators", null=True
                    ),
                ),
                (
                    "microwave_count",
                    models.IntegerField(default=0, help_text="Count of microwaves"),
                ),
                (
                    "microwave_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for microwaves", null=True
                    ),
                ),
                (
                    "induction_count",
                    models.IntegerField(
                        default=0, help_text="Count of induction cooktops"
                    ),
                ),
                (
                    "induction_watt",
                    models.FloatField(
                        blank=True,
                        help_text="Wattage for induction cooktops",
                        null=True,
                    ),
                ),
                ("tv_count", models.IntegerField(default=0, help_text="Count of TVs")),
                (
                    "tv_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for TVs", null=True
                    ),
                ),
                (
                    "others_count",
                    models.IntegerField(default=0, help_text="Count of other devices"),
                ),
                (
                    "others_watt",
                    models.FloatField(
                        blank=True, help_text="Wattage for other devices", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Detailed Device Record",
                "verbose_name_plural": "Detailed Device Records",
                "db_table": "detailed_device_records",
                "ordering": ["building", "room"],
                "indexes": [
                    models.Index(
                        fields=["building", "room"],
                        name="detailed_de_buildin_b93abc_idx",
                    ),
                    models.Index(
                        fields=["building"], name="detailed_de_buildin_451e0a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="detailed_de_created_8ac7c2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building", "room"), name="unique_building_room_combo"
                    )
                ],
            },
        ),
    ]
