# Generated by Django 5.2.10 on 2026-02-11 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0003_detaileddevicerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Device Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("floor", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["building", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="usage",
            name="appliance",
        ),
        migrations.DeleteModel(
            name="DetailedDeviceRecord",
        ),
        migrations.RemoveField(
            model_name="emission",
            name="usage",
        ),
        migrations.RemoveField(
            model_name="energyusage",
            name="device",
        ),
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="device",
            name="hours_used_per_day",
        ),
        migrations.AddField(
            model_name="device",
            name="iseer",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="star_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="ton",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("AC", "Air Conditioner"),
                    ("FAN", "Fan"),
                    ("LIGHT", "Light"),
                    ("PC", "Computer"),
                    ("ELECTRONICS", "Electronics"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="watt_rating",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="energy.brand",
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["name"], name="energy_buil_name_ebd7f2_idx"),
        ),
        migrations.AlterField(
            model_name="device",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="energy.building",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="energy.devicecategory",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="energy.building",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="energy.room",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type", "building", "room"],
                name="energy_devi_device__89ee74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["brand"], name="energy_devi_brand_i_821392_idx"),
        ),
        migrations.DeleteModel(
            name="Appliance",
        ),
        migrations.DeleteModel(
            name="Emission",
        ),
        migrations.DeleteModel(
            name="Usage",
        ),
        migrations.DeleteModel(
            name="EnergyUsage",
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["building", "name"], name="energy_room_buildin_0475f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("building", "name")},
        ),
    ]
