# Generated by Django 5.2.10 on 2026-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building", models.CharField(max_length=100)),
                ("room", models.CharField(max_length=50)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("FAN", "Fan"),
                            ("AC", "Air Conditioner"),
                            ("LIGHT", "Light"),
                            ("PC", "Computer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("watt_rating", models.FloatField()),
                ("hours_used_per_day", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
