# Generated by Django 5.2.10 on 2026-02-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_brand_building_devicecategory_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
