# Generated by Django 5.2.10 on 2026-02-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0005_alter_device_device_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("target_kg", models.FloatField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_targets",
                        to="energy.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ESGReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("total_energy_kwh", models.FloatField()),
                ("total_carbon_kg", models.FloatField()),
                ("target_kg", models.FloatField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="esg_reports/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esg_reports",
                        to="energy.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_used", models.FloatField()),
                ("energy_kwh", models.FloatField(blank=True, null=True)),
                ("carbon_kg", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="energy.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("device", "date")},
            },
        ),
    ]
