# Generated by Django 5.2.10 on 2026-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0006_carbontarget_esgreport_usagelog"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="building",
            name="energy_buil_name_ebd7f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="room",
            name="energy_room_buildin_0475f9_idx",
        ),
        migrations.AddField(
            model_name="esgreport",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done"), ("error", "Error")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="esgreport",
            name="total_carbon_kg",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="esgreport",
            name="total_energy_kwh",
            field=models.FloatField(default=0),
        ),
    ]
