# Generated by Django 5.2.10 on 2026-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0007_add_esgreport_status_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLSystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARN", "Warning"),
                            ("ERROR", "Error - Action Required"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("metrics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("predicted_power_kw", models.FloatField()),
                ("p10_kw", models.FloatField(blank=True, null=True)),
                ("p90_kw", models.FloatField(blank=True, null=True)),
                ("features_snapshot", models.JSONField(default=dict)),
                ("target_actual_kw", models.FloatField(blank=True, null=True)),
                ("residual_kw", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
