# Generated by Django 6.0.2 on 2026-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0008_mlsystemevent_predictionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="esgreport",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="esgreport",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="esgreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="usagelog",
            index=models.Index(
                fields=["device", "date"], name="energy_usag_device__95ea73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagelog",
            index=models.Index(fields=["date"], name="energy_usag_date_f2c6ea_idx"),
        ),
    ]
