# Generated by Django 6.0.2 on 2026-04-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0009_esgreport_celery_task_id_esgreport_error_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonEmissionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("scope1", "Scope 1"), ("scope2", "Scope 2")],
                        max_length=8,
                    ),
                ),
                ("emission_factor", models.FloatField()),
                ("carbon_kg", models.FloatField()),
                (
                    "usage_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="energy.usagelog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutputLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("output_value", models.FloatField()),
                ("output_unit", models.CharField(max_length=32)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="energy.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.CharField(max_length=64)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.FloatField()),
                ("is_fallback", models.BooleanField(default=False)),
                ("result_json", models.JSONField()),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="energy.esgreport",
                    ),
                ),
            ],
        ),
    ]
