# Generated by Django 5.2.10 on 2026-01-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("power_rating", models.FloatField(help_text="Watts")),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_used", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "energy_consumed",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=10
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_usages",
                        to="energy.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_used", models.FloatField()),
                ("date", models.DateField()),
                ("season", models.CharField(max_length=10)),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="energy.appliance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy_kwh", models.FloatField()),
                ("co2_kg", models.FloatField()),
                (
                    "usage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="energy.usage"
                    ),
                ),
            ],
        ),
    ]
